#############################################################################
# Makefile for building: NiceCopier
# Generated by qmake (3.0) (Qt 5.1.0) on: sex 11. Out 21:09:25 2013
# Project:  NiceCopier.pro
# Template: app
# Command: E:/programming/tools/qt/qt-64bit/qtbase/bin/qmake.exe -spec win32-g++ CONFIG+=release64 -o Makefile NiceCopier.pro
#############################################################################

MAKEFILE      = Makefile

first: release
install: release-install
uninstall: release-uninstall
QMAKE         = E:/programming/tools/qt/qt-64bit/qtbase/bin/qmake.exe
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = cp -f
INSTALL_PROGRAM = cp -f
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = 
DEL_DIR       = rmdir
MOVE          = mv -f
SUBTARGETS    =  \
		release \
		debug


release: FORCE
	$(MAKE) -f $(MAKEFILE).Release
release-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Release 
release-all: FORCE
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: FORCE
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Release uninstall
debug: FORCE
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Debug 
debug-all: FORCE
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: FORCE
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Debug uninstall

Makefile: NiceCopier.pro ../../../../tools/qt/qt-64bit/qtbase/mkspecs/win32-g++/qmake.conf ../../../../tools/qt/qt-64bit/qtbase/mkspecs/features/spec_pre.prf \
		../../../../tools/qt/qt-64bit/qtbase/mkspecs/qdevice.pri \
		../../../../tools/qt/qt-64bit/qtbase/mkspecs/features/device_config.prf \
		../../../../tools/qt/qt-64bit/qtbase/mkspecs/common/shell-unix.conf \
		../../../../tools/qt/qt-64bit/qtbase/mkspecs/qconfig.pri \
		../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules-inst/qt_lib_axbase.pri \
		../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules/qt_lib_axbase.pri \
		../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules-inst/qt_lib_axcontainer.pri \
		../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules/qt_lib_axcontainer.pri \
		../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules-inst/qt_lib_axserver.pri \
		../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules/qt_lib_axserver.pri \
		../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules/qt_lib_bootstrap.pri \
		../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules/qt_lib_core.pri \
		../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules/qt_lib_gui.pri \
		../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules/qt_lib_network.pri \
		../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules/qt_lib_platformsupport.pri \
		../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules-inst/qt_lib_qml.pri \
		../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules/qt_lib_qml.pri \
		../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules-inst/qt_lib_script.pri \
		../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules/qt_lib_script.pri \
		../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules-inst/qt_lib_scripttools.pri \
		../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules/qt_lib_scripttools.pri \
		../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules-inst/qt_lib_serialport.pri \
		../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules/qt_lib_serialport.pri \
		../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules/qt_lib_sql.pri \
		../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules-inst/qt_lib_svg.pri \
		../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules/qt_lib_svg.pri \
		../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules/qt_lib_testlib.pri \
		../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules-inst/qt_lib_v8.pri \
		../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules/qt_lib_v8.pri \
		../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules/qt_lib_widgets.pri \
		../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules/qt_lib_xml.pri \
		../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules-inst/qt_lib_xmlpatterns.pri \
		../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules/qt_plugin_qgenericbearer.pri \
		../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules/qt_plugin_qico.pri \
		../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules/qt_plugin_qminimal.pri \
		../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules/qt_plugin_qmldbg_tcp.pri \
		../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules/qt_plugin_qmng.pri \
		../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules/qt_plugin_qnativewifibearer.pri \
		../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules/qt_plugin_qoffscreen.pri \
		../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules/qt_plugin_qsvg.pri \
		../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules/qt_plugin_qsvgicon.pri \
		../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules/qt_plugin_qtaccessiblewidgets.pri \
		../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules/qt_plugin_qtga.pri \
		../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules/qt_plugin_qtiff.pri \
		../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules/qt_plugin_qwbmp.pri \
		../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules/qt_plugin_qwindows.pri \
		../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules/qt_plugin_windowsprintersupport.pri \
		../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules/qt_tool_dumpcpp.pri \
		../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules/qt_tool_dumpdoc.pri \
		../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules/qt_tool_idc.pri \
		../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules/qt_tool_qdoc.pri \
		../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules/qt_tool_uic.pri \
		../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules/qt_tool_xmlpatterns.pri \
		../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules/qt_tool_xmlpatternsvalidator.pri \
		../../../../tools/qt/qt-64bit/qtbase/mkspecs/features/qt_functions.prf \
		../../../../tools/qt/qt-64bit/qtbase/mkspecs/features/qt_config.prf \
		../../../../tools/qt/qt-64bit/qtbase/mkspecs/win32-g++/qmake.conf \
		../../../../tools/qt/qt-64bit/qtbase/mkspecs/features/spec_post.prf \
		../../../../tools/qt/qt-64bit/qtbase/mkspecs/features/exclusive_builds.prf \
		../../../../tools/qt/qt-64bit/qtbase/mkspecs/features/default_pre.prf \
		../../../../tools/qt/qt-64bit/qtbase/mkspecs/features/win32/default_pre.prf \
		../../../../tools/qt/qt-64bit/qtbase/mkspecs/features/resolve_config.prf \
		../../../../tools/qt/qt-64bit/qtbase/mkspecs/features/default_post.prf \
		../../../../tools/qt/qt-64bit/qtbase/mkspecs/features/win32/rtti.prf \
		../../../../tools/qt/qt-64bit/qtbase/mkspecs/features/warn_on.prf \
		../../../../tools/qt/qt-64bit/qtbase/mkspecs/features/qt.prf \
		../../../../tools/qt/qt-64bit/qtbase/mkspecs/features/resources.prf \
		../../../../tools/qt/qt-64bit/qtbase/mkspecs/features/moc.prf \
		../../../../tools/qt/qt-64bit/qtbase/mkspecs/features/uic.prf \
		../../../../tools/qt/qt-64bit/qtbase/mkspecs/features/win32/windows.prf \
		../../../../tools/qt/qt-64bit/qtbase/mkspecs/features/testcase_targets.prf \
		../../../../tools/qt/qt-64bit/qtbase/mkspecs/features/exceptions.prf \
		../../../../tools/qt/qt-64bit/qtbase/mkspecs/features/yacc.prf \
		../../../../tools/qt/qt-64bit/qtbase/mkspecs/features/lex.prf \
		NiceCopier.pro \
		E:/programming/tools/qt/qt-64bit/qtbase/plugins/imageformats/qico.prl \
		E:/programming/tools/qt/qt-64bit/qtbase/lib/Qt5Gui.prl \
		E:/programming/tools/qt/qt-64bit/qtbase/lib/Qt5Core.prl \
		E:/programming/tools/qt/qt-64bit/qtbase/plugins/platforms/qwindows.prl \
		E:/programming/tools/qt/qt-64bit/qtbase/lib/Qt5PlatformSupport.prl \
		E:/programming/tools/qt/qt-64bit/qtbase/lib/Qt5Widgets.prl \
		E:/programming/tools/qt/qt-64bit/qtbase/lib/Qt5Xml.prl \
		E:/programming/tools/qt/qt-64bit/qtbase/lib/Qt5Network.prl
	$(QMAKE) -spec win32-g++ CONFIG+=release64 -o Makefile NiceCopier.pro
../../../../tools/qt/qt-64bit/qtbase/mkspecs/features/spec_pre.prf:
../../../../tools/qt/qt-64bit/qtbase/mkspecs/qdevice.pri:
../../../../tools/qt/qt-64bit/qtbase/mkspecs/features/device_config.prf:
../../../../tools/qt/qt-64bit/qtbase/mkspecs/common/shell-unix.conf:
../../../../tools/qt/qt-64bit/qtbase/mkspecs/qconfig.pri:
../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules-inst/qt_lib_axbase.pri:
../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules/qt_lib_axbase.pri:
../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules-inst/qt_lib_axcontainer.pri:
../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules/qt_lib_axcontainer.pri:
../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules-inst/qt_lib_axserver.pri:
../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules/qt_lib_axserver.pri:
../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules/qt_lib_bootstrap.pri:
../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules/qt_lib_concurrent.pri:
../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules/qt_lib_core.pri:
../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules/qt_lib_gui.pri:
../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules/qt_lib_network.pri:
../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules/qt_lib_platformsupport.pri:
../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules/qt_lib_printsupport.pri:
../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules-inst/qt_lib_qml.pri:
../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules/qt_lib_qml.pri:
../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules-inst/qt_lib_script.pri:
../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules/qt_lib_script.pri:
../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules-inst/qt_lib_scripttools.pri:
../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules/qt_lib_scripttools.pri:
../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules-inst/qt_lib_serialport.pri:
../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules/qt_lib_serialport.pri:
../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules/qt_lib_sql.pri:
../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules-inst/qt_lib_svg.pri:
../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules/qt_lib_svg.pri:
../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules/qt_lib_testlib.pri:
../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules-inst/qt_lib_v8.pri:
../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules/qt_lib_v8.pri:
../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules/qt_lib_widgets.pri:
../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules/qt_lib_xml.pri:
../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules-inst/qt_lib_xmlpatterns.pri:
../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules/qt_plugin_qgenericbearer.pri:
../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules/qt_plugin_qico.pri:
../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules/qt_plugin_qminimal.pri:
../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules/qt_plugin_qmldbg_tcp.pri:
../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules/qt_plugin_qmng.pri:
../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules/qt_plugin_qnativewifibearer.pri:
../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules/qt_plugin_qoffscreen.pri:
../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules/qt_plugin_qsvg.pri:
../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules/qt_plugin_qsvgicon.pri:
../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules/qt_plugin_qtaccessiblewidgets.pri:
../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules/qt_plugin_qtga.pri:
../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules/qt_plugin_qtiff.pri:
../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules/qt_plugin_qwbmp.pri:
../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules/qt_plugin_qwindows.pri:
../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules/qt_plugin_windowsprintersupport.pri:
../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules/qt_tool_dumpcpp.pri:
../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules/qt_tool_dumpdoc.pri:
../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules/qt_tool_idc.pri:
../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules/qt_tool_qdoc.pri:
../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules/qt_tool_uic.pri:
../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules/qt_tool_xmlpatterns.pri:
../../../../tools/qt/qt-64bit/qtbase/mkspecs/modules/qt_tool_xmlpatternsvalidator.pri:
../../../../tools/qt/qt-64bit/qtbase/mkspecs/features/qt_functions.prf:
../../../../tools/qt/qt-64bit/qtbase/mkspecs/features/qt_config.prf:
../../../../tools/qt/qt-64bit/qtbase/mkspecs/win32-g++/qmake.conf:
../../../../tools/qt/qt-64bit/qtbase/mkspecs/features/spec_post.prf:
../../../../tools/qt/qt-64bit/qtbase/mkspecs/features/exclusive_builds.prf:
../../../../tools/qt/qt-64bit/qtbase/mkspecs/features/default_pre.prf:
../../../../tools/qt/qt-64bit/qtbase/mkspecs/features/win32/default_pre.prf:
../../../../tools/qt/qt-64bit/qtbase/mkspecs/features/resolve_config.prf:
../../../../tools/qt/qt-64bit/qtbase/mkspecs/features/default_post.prf:
../../../../tools/qt/qt-64bit/qtbase/mkspecs/features/win32/rtti.prf:
../../../../tools/qt/qt-64bit/qtbase/mkspecs/features/warn_on.prf:
../../../../tools/qt/qt-64bit/qtbase/mkspecs/features/qt.prf:
../../../../tools/qt/qt-64bit/qtbase/mkspecs/features/resources.prf:
../../../../tools/qt/qt-64bit/qtbase/mkspecs/features/moc.prf:
../../../../tools/qt/qt-64bit/qtbase/mkspecs/features/uic.prf:
../../../../tools/qt/qt-64bit/qtbase/mkspecs/features/win32/windows.prf:
../../../../tools/qt/qt-64bit/qtbase/mkspecs/features/testcase_targets.prf:
../../../../tools/qt/qt-64bit/qtbase/mkspecs/features/exceptions.prf:
../../../../tools/qt/qt-64bit/qtbase/mkspecs/features/yacc.prf:
../../../../tools/qt/qt-64bit/qtbase/mkspecs/features/lex.prf:
NiceCopier.pro:
E:/programming/tools/qt/qt-64bit/qtbase/plugins/imageformats/qico.prl:
E:/programming/tools/qt/qt-64bit/qtbase/lib/Qt5Gui.prl:
E:/programming/tools/qt/qt-64bit/qtbase/lib/Qt5Core.prl:
E:/programming/tools/qt/qt-64bit/qtbase/plugins/platforms/qwindows.prl:
E:/programming/tools/qt/qt-64bit/qtbase/lib/Qt5PlatformSupport.prl:
E:/programming/tools/qt/qt-64bit/qtbase/lib/Qt5Widgets.prl:
E:/programming/tools/qt/qt-64bit/qtbase/lib/Qt5Xml.prl:
E:/programming/tools/qt/qt-64bit/qtbase/lib/Qt5Network.prl:
qmake: FORCE
	@$(QMAKE) -spec win32-g++ CONFIG+=release64 -o Makefile NiceCopier.pro

qmake_all: FORCE

make_first: release-make_first debug-make_first FORCE
all: release-all debug-all FORCE
clean: release-clean debug-clean FORCE
distclean: release-distclean debug-distclean FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) E:/programming/projects/nicecopier/application/NiceCopier/nicecopier_plugin_import.cpp

release-mocclean:
	$(MAKE) -f $(MAKEFILE).Release mocclean
debug-mocclean:
	$(MAKE) -f $(MAKEFILE).Debug mocclean
mocclean: release-mocclean debug-mocclean

release-mocables:
	$(MAKE) -f $(MAKEFILE).Release mocables
debug-mocables:
	$(MAKE) -f $(MAKEFILE).Debug mocables
mocables: release-mocables debug-mocables

check: first
FORCE:

$(MAKEFILE).Release: Makefile
$(MAKEFILE).Debug: Makefile
